#ifndef INT_VECTOR_H
#define INT_VECTOR_H
//2014-03-28  17:20 文件创建
//2014-03-28  17:22 加入stm8s105中断矢量
//2014-03-28  17:35 加入STM8S103,STM8S003,STM8S207,STM8S208,STM8L101,STM8L152中断矢量
//************************************************************************************
#if defined(STM8S103) || defined(STM8S003)	//2014-03-28 by zpyws
	#define SPI_TXE_vector                       0x0C
	#define SPI_RXNE_vector                      0x0C
	#define SPI_WKUP_vector                      0x0C
	#define SPI_MODF_vector                      0x0C
	#define SPI_CRCERR_vector                    0x0C
	#define SPI_OVR_vector                       0x0C
	#define TIM1_CAPCOM_TIF_vector               0x0D
	#define TIM1_CAPCOM_BIF_vector               0x0D
	#define TIM1_OVR_UIF_vector                  0x0D
	#define TIM1_CAPCOM_COMIF_vector             0x0E
	#define TIM1_CAPCOM_CC2IF_vector             0x0E
	#define TIM1_CAPCOM_CC3IF_vector             0x0E
	#define TIM1_CAPCOM_CC4IF_vector             0x0E
	#define TIM1_CAPCOM_CC1IF_vector             0x0E
	#define TIM2_OVR_UIF_vector                  0x0F
	#define TIM2_CAPCOM_CC1IF_vector             0x10
	#define TIM2_CAPCOM_TIF_vector               0x10
	#define TIM2_CAPCOM_CC2IF_vector             0x10
	#define TIM2_CAPCOM_CC3IF_vector             0x10
	#define UART1_T_TXE_vector                   0x13
	#define UART1_T_TC_vector                    0x13
	#define UART1_R_OR_vector                    0x14
	#define UART1_R_RXNE_vector                  0x14
	#define UART1_R_IDLE_vector                  0x14
	#define UART1_R_PE_vector                    0x14
	#define UART1_R_LBDF_vector                  0x14
	#define I2C_ADD10_vector                     0x15
	#define I2C_ADDR_vector                      0x15
	#define I2C_OVR_vector                       0x15
	#define I2C_STOPF_vector                     0x15
	#define I2C_BTF_vector                       0x15
	#define I2C_WUFH_vector                      0x15
	#define I2C_RXNE_vector                      0x15
	#define I2C_TXE_vector                       0x15
	#define I2C_BERR_vector                      0x15
	#define I2C_ARLO_vector                      0x15
	#define I2C_AF_vector                        0x15
	#define I2C_SB_vector                        0x15
	#define ADC1_AWS0_vector                     0x18
	#define ADC1_AWS1_vector                     0x18
	#define ADC1_AWS2_vector                     0x18
	#define ADC1_AWS3_vector                     0x18
	#define ADC1_AWS4_vector                     0x18
	#define ADC1_AWS5_vector                     0x18
	#define ADC1_AWS6_vector                     0x18
	#define ADC1_EOC_vector                      0x18
	#define ADC1_AWS8_vector                     0x18
	#define ADC1_AWS9_vector                     0x18
	#define ADC1_AWDG_vector                     0x18
	#define ADC1_AWS7_vector                     0x18
	#define TIM4_OVR_UIF_vector                  0x19
	#define FLASH_EOP_vector                     0x1A
	#define FLASH_WR_PG_DIS_vector               0x1A
#elif defined(STM8S105)	//2014-03-28  by zpyws
	#define SPI_TXE_vector                       0x0C
	#define SPI_RXNE_vector                      0x0C
	#define SPI_WKUP_vector                      0x0C
	#define SPI_MODF_vector                      0x0C
	#define SPI_CRCERR_vector                    0x0C
	#define SPI_OVR_vector                       0x0C
	#define TIM1_OVR_TIF_vector                  0x0D
	#define TIM1_OVR_BIF_vector                  0x0D
	#define TIM1_OVR_UIF_vector                  0x0D
	#define TIM1_CAPCOM_CC1IF_vector             0x0E
	#define TIM1_CAPCOM_CC2IF_vector             0x0E
	#define TIM1_CAPCOM_COMIF_vector             0x0E
	#define TIM1_CAPCOM_CC4IF_vector             0x0E
	#define TIM1_CAPCOM_CC3IF_vector             0x0E
	#define TIM2_OVR_UIF_vector                  0x0F
	#define TIM3_OVR_UIF_vector                  0x11
	#define TIM2_CAPCOM_CC3IF_vector             0x10
	#define TIM3_CAPCOM_CC3IF_vector             0x12
	#define TIM2_CAPCOM_CC1IF_vector             0x10
	#define TIM2_CAPCOM_TIF_vector               0x10
	#define TIM3_CAPCOM_TIF_vector               0x12
	#define TIM3_CAPCOM_CC1IF_vector             0x12
	#define TIM3_CAPCOM_CC2IF_vector             0x12
	#define TIM2_CAPCOM_CC2IF_vector             0x10
	#define I2C_SB_vector                        0x15
	#define I2C_ADDR_vector                      0x15
	#define I2C_ADD10_vector                     0x15
	#define I2C_STOPF_vector                     0x15
	#define I2C_BTF_vector                       0x15
	#define I2C_OVR_vector                       0x15
	#define I2C_RXNE_vector                      0x15
	#define I2C_TXE_vector                       0x15
	#define I2C_BERR_vector                      0x15
	#define I2C_ARLO_vector                      0x15
	#define I2C_AF_vector                        0x15
	#define I2C_WUFH_vector                      0x15
	#define UART2_T_TXE_vector                   0x16
	#define UART2_T_TC_vector                    0x16
	#define UART2_R_OR_vector                    0x17
	#define UART2_R_RXNE_vector                  0x17
	#define UART2_R_IDLE_vector                  0x17
	#define UART2_R_PE_vector                    0x17
	#define UART2_R_LBDF_vector                  0x17
	#define ADC1_AWS2_vector                     0x18
	#define ADC1_AWS1_vector                     0x18
	#define ADC1_AWS0_vector                     0x18
	#define ADC1_AWS3_vector                     0x18
	#define ADC1_EOC_vector                      0x18
	#define ADC1_AWS5_vector                     0x18
	#define ADC1_AWS6_vector                     0x18
	#define ADC1_AWS7_vector                     0x18
	#define ADC1_AWS8_vector                     0x18
	#define ADC1_AWS9_vector                     0x18
	#define ADC1_AWDG_vector                     0x18
	#define ADC1_AWS4_vector                     0x18
	#define TIM4_OVR_UIF_vector                  0x19
	#define FLASH_EOP_vector                     0x1A
	#define FLASH_WR_PG_DIS_vector               0x1A
#elif defined(STM8S207)
	#define AWU_vector                           0x03
	#define CLK_CSS_vector                       0x04
	#define CLK_SWITCH_vector                    0x04
	#define SPI_RXNE_vector                      0x0C
	#define SPI_TXE_vector                       0x0C
	#define SPI_WKUP_vector                      0x0C
	#define SPI_MODF_vector                      0x0C
	#define SPI_OVR_vector                       0x0C
	#define SPI_CRCERR_vector                    0x0C
	#define TIM1_OVR_UIF_vector                  0x0D
	#define TIM1_CAPCOM_BIF_vector               0x0D
	#define TIM1_CAPCOM_TIF_vector               0x0D
	#define TIM1_CAPCOM_CC1IF_vector             0x0E
	#define TIM1_CAPCOM_CC2IF_vector             0x0E
	#define TIM1_CAPCOM_CC3IF_vector             0x0E
	#define TIM1_CAPCOM_CC4IF_vector             0x0E
	#define TIM1_CAPCOM_COMIF_vector             0x0E
	#define TIM2_OVR_UIF_vector                  0x0F
	#define TIM2_CAPCOM_TIF_vector               0x10
	#define TIM2_CAPCOM_CC1IF_vector             0x10
	#define TIM2_CAPCOM_CC2IF_vector             0x10
	#define TIM2_CAPCOM_CC3IF_vector             0x10
	#define TIM3_OVR_UIF_vector                  0x11
	#define TIM3_CAPCOM_CC1IF_vector             0x12
	#define TIM3_CAPCOM_TIF_vector               0x12
	#define TIM3_CAPCOM_CC3IF_vector             0x12
	#define TIM3_CAPCOM_CC2IF_vector             0x12
	#define UART1_T_TXE_vector                   0x13
	#define UART1_T_TC_vector                    0x13
	#define UART1_R_OR_vector                    0x14
	#define UART1_R_LBDF_vector                  0x14
	#define UART1_R_IDLE_vector                  0x14
	#define UART1_R_PE_vector                    0x14
	#define UART1_R_RXNE_vector                  0x14
	#define I2C_SB_vector                        0x15
	#define I2C_ADDR_vector                      0x15
	#define I2C_ADD10_vector                     0x15
	#define I2C_STOPF_vector                     0x15
	#define I2C_BTF_vector                       0x15
	#define I2C_WUFH_vector                      0x15
	#define I2C_OVR_vector                       0x15
	#define I2C_TXE_vector                       0x15
	#define I2C_BERR_vector                      0x15
	#define I2C_ARLO_vector                      0x15
	#define I2C_AF_vector                        0x15
	#define I2C_RXNE_vector                      0x15
	#define UART3_T_TC_vector                    0x16
	#define UART3_T_TXE_vector                   0x16
	#define UART3_R_RXNE_vector                  0x17
	#define UART3_R_OR_vector                    0x17
	#define UART3_R_IDLE_vector                  0x17
	#define UART3_R_PE_vector                    0x17
	#define UART3_R_LBDF_vector                  0x17
	#define UART3_R_LHDF_vector                  0x17
	#define ADC2_AWDG_vector                     0x18
	#define ADC2_EOC_vector                      0x18
	#define TIM4_OVR_UIF_vector                  0x19
	#define FLASH_EOP_vector                     0x1A
	#define FLASH_WR_PG_DIS_vector               0x1A
#elif defined(STM8S208)
	#define AWU_vector                           0x03
	#define CLK_CSS_vector                       0x04
	#define CLK_SWITCH_vector                    0x04
	#define beCAN_FMP_vector                     0x0A
	#define beCAN_FULL_vector                    0x0A
	#define beCAN_FOVR_vector                    0x0A
	#define beCAN_EWGF_vector                    0x0B
	#define beCAN_EPVF_vector                    0x0B
	#define beCAN_BOFF_vector                    0x0B
	#define beCAN_LEC0_vector                    0x0B
	#define beCAN_LEC1_vector                    0x0B
	#define beCAN_LEC2_vector                    0x0B
	#define beCAN_RQCP0_vector                   0x0B
	#define beCAN_RQCP1_vector                   0x0B
	#define beCAN_RQCP2_vector                   0x0B
	#define beCAN_WKUI_vector                    0x0B
	#define SPI_TXE_vector                       0x0C
	#define SPI_RXNE_vector                      0x0C
	#define SPI_WKUP_vector                      0x0C
	#define SPI_MODF_vector                      0x0C
	#define SPI_OVR_vector                       0x0C
	#define SPI_CRCERR_vector                    0x0C
	#define TIM1_OVR_UIF_vector                  0x0D
	#define TIM1_CAPCOM_BIF_vector               0x0D
	#define TIM1_CAPCOM_TIF_vector               0x0D
	#define TIM1_CAPCOM_CC1IF_vector             0x0E
	#define TIM1_CAPCOM_CC2IF_vector             0x0E
	#define TIM1_CAPCOM_CC3IF_vector             0x0E
	#define TIM1_CAPCOM_CC4IF_vector             0x0E
	#define TIM1_CAPCOM_COMIF_vector             0x0E
	#define TIM2_OVR_UIF_vector                  0x0F
	#define TIM2_CAPCOM_TIF_vector               0x10
	#define TIM2_CAPCOM_CC1IF_vector             0x10
	#define TIM2_CAPCOM_CC2IF_vector             0x10
	#define TIM2_CAPCOM_CC3IF_vector             0x10
	#define TIM3_OVR_UIF_vector                  0x11
	#define TIM3_CAPCOM_TIF_vector               0x12
	#define TIM3_CAPCOM_CC1IF_vector             0x12
	#define TIM3_CAPCOM_CC2IF_vector             0x12
	#define TIM3_CAPCOM_CC3IF_vector             0x12
	#define UART1_T_TXE_vector                   0x13
	#define UART1_T_TC_vector                    0x13
	#define UART1_R_RXNE_vector                  0x14
	#define UART1_R_OR_vector                    0x14
	#define UART1_R_IDLE_vector                  0x14
	#define UART1_R_PE_vector                    0x14
	#define UART1_R_LBDF_vector                  0x14
	#define I2C_SB_vector                        0x15
	#define I2C_ADDR_vector                      0x15
	#define I2C_ADD10_vector                     0x15
	#define I2C_STOPF_vector                     0x15
	#define I2C_BTF_vector                       0x15
	#define I2C_WUFH_vector                      0x15
	#define I2C_RXNE_vector                      0x15
	#define I2C_TXE_vector                       0x15
	#define I2C_BERR_vector                      0x15
	#define I2C_ARLO_vector                      0x15
	#define I2C_AF_vector                        0x15
	#define I2C_OVR_vector                       0x15
	#define UART3_T_TXE_vector                   0x16
	#define UART3_T_TC_vector                    0x16
	#define UART3_R_RXNE_vector                  0x17
	#define UART3_R_OR_vector                    0x17
	#define UART3_R_IDLE_vector                  0x17
	#define UART3_R_PE_vector                    0x17
	#define UART3_R_LBDF_vector                  0x17
	#define UART3_R_LHDF_vector                  0x17
	#define ADC2_AWDG_vector                     0x18
	#define ADC2_EOC_vector                      0x18
	#define TIM4_OVR_UIF_vector                  0x19
	#define FLASH_EOP_vector                     0x1A
	#define FLASH_WR_PG_DIS_vector               0x1A
#elif defined(STM8L101)	//2014-03-28 by zpyws
	#define FLASH_EOP_vector                     0x03
	#define FLASH_WR_PG_DIS_vector               0x03
	#define AWU_vector                           0x06
	#define EXTIB_vector                         0x08
	#define EXTID_vector                         0x09
	#define EXTI0_vector                         0x0A
	#define EXTI1_vector                         0x0B
	#define EXTI2_vector                         0x0C
	#define EXTI3_vector                         0x0D
	#define EXTI4_vector                         0x0E
	#define EXTI5_vector                         0x0F
	#define EXTI6_vector                         0x10
	#define EXTI7_vector                         0x11
	#define COMP_ITEN2_vector                    0x14
	#define COMP_ITEN1_vector                    0x14
	#define TIM2_OVR_UIF_vector                  0x15
	#define TIM2_CAPCOM_TIF_vector               0x16
	#define TIM2_CAPCOM_BIF_vector               0x16
	#define TIM2_CAPCOM_CC2IF_vector             0x16
	#define TIM2_CAPCOM_CC1IF_vector             0x16
	#define TIM3_OVR_UIF_vector                  0x17
	#define TIM3_CAPCOM_BIF_vector               0x18
	#define TIM3_CAPCOM_TIF_vector               0x18
	#define TIM3_CAPCOM_CC1IF_vector             0x18
	#define TIM3_CAPCOM_CC2IF_vector             0x18
	#define TIM4_UIF_vector                      0x1B
	#define TIM4_TIF_vector                      0x1B
	#define SPI_TXE_vector                       0x1C
	#define SPI_RXNE_vector                      0x1C
	#define SPI_WKUP_vector                      0x1C
	#define SPI_OVR_vector                       0x1C
	#define SPI_MODF_vector                      0x1C
	#define USART_T_TC_vector                    0x1D
	#define USART_T_TXE_vector                   0x1D
	#define USART_R_RXNE_vector                  0x1E
	#define USART_R_OR_vector                    0x1E
	#define USART_R_IDLE_vector                  0x1E
	#define USART_R_PE_vector                    0x1E
	#define I2C_SB_vector                        0x1F
	#define I2C_ADDR_vector                      0x1F
	#define I2C_ADD10_vector                     0x1F
	#define I2C_STOPF_vector                     0x1F
	#define I2C_BTF_vector                       0x1F
	#define I2C_WUFH_vector                      0x1F
	#define I2C_RXNE_vector                      0x1F
	#define I2C_TXE_vector                       0x1F
	#define I2C_BERR_vector                      0x1F
	#define I2C_ARLO_vector                      0x1F
	#define I2C_AF_vector                        0x1F
	#define I2C_OVR_vector                       0x1F
#elif defined(STM8L152)//2014-03-28  BY ZPYWS
	#define FLASH_EOP_vector                     0x01
	#define FLASH_WR_PG_DIS_vector               0x01
	#define EXTIE_vector                         0x05
	#define EXTIF_vector                         0x05
	#define EXTIPVD_vector                       0x05
	#define EXTIB_vector                         0x06
	#define EXTIG_vector                         0x06
	#define EXTID_vector                         0x07
	#define EXTID_vector                         0x07
	#define EXTI0_vector                         0x08
	#define EXTI1_vector                         0x09
	#define EXTI2_vector                         0x0A
	#define EXTI3_vector                         0x0B
	#define EXTI4_vector                         0x0C
	#define EXTI5_vector                         0x0D
	#define EXTI6_vector                         0x0E
	#define EXTI7_vector                         0x0F
	#define LCD_SOF_vector                       0x10
	#define CLK_CSS_vector                       0x11
	#define CLK_SWITCH_vector                    0x11
	#define TIM1_BIF_vector                      0x11
	#define DAC_DMAUDR1_vector                   0x11
	#define DAC_DMAUDR2_vector                   0x11
	#define COMP_EF1_vector                      0x12
	#define COMP_EF2_vector                      0x12
	#define ADC_EOC_vector                       0x12
	#define ADC_OVER_vector                      0x12
	#define TIM2_OVR_UIF_vector                  0x13
	#define USART2_T_TXE_vector                  0x13
	#define USART2_T_TC_vector                   0x13
	#define TIM2_CAPCOM_BIF_vector               0x14
	#define TIM2_CAPCOM_TIF_vector               0x14
	#define TIM2_CAPCOM_CC2IF_vector             0x14
	#define TIM2_CAPCOM_CC1IF_vector             0x14
	#define USART2_R_RXNE_vector                 0x14
	#define USART2_R_OR_vector                   0x14
	#define USART2_R_IDLE_vector                 0x14
	#define USART2_R_PE_vector                   0x14
	#define TIM3_OVR_UIF_vector                  0x15
	#define USART3_T_TXE_vector                  0x15
	#define USART3_T_TC_vector                   0x15
	#define TIM3_CAPCOM_BIF_vector               0x16
	#define TIM3_CAPCOM_TIF_vector               0x16
	#define TIM3_CAPCOM_CC2IF_vector             0x16
	#define TIM3_CAPCOM_CC1IF_vector             0x16
	#define USART3_R_RXNE_vector                 0x16
	#define USART3_R_OR_vector                   0x16
	#define USART3_R_IDLE_vector                 0x16
	#define USART3_R_PE_vector                   0x16
	#define TIM1_OVR_UIF_vector                  0x17
	#define TIM1_CAPCOM_TIF_vector               0x18
	#define TIM1_CAPCOM_CC4IF_vector             0x18
	#define TIM1_CAPCOM_CC3IF_vector             0x18
	#define TIM1_CAPCOM_CC2IF_vector             0x18
	#define TIM1_CAPCOM_CC1IF_vector             0x18
	#define TIM1_CAPCOM_COMIF_vector             0x18
	#define TIM4_TIF_vector                      0x19
	#define TIM4_UIF_vector                      0x19
	#define SPI_TXE_vector                       0x1A
	#define SPI_RXNE_vector                      0x1A
	#define SPI_WKUP_vector                      0x1A
	#define SPI_MODF_vector                      0x1A
	#define SPI_OVR_vector                       0x1A
	#define TIM5_OVR_UIF_vector                  0x1B
	#define USART1_T_TXE_vector                  0x1B
	#define USART1_T_TC_vector                   0x1B
	#define TIM5_CAPCOM_BIF_vector               0x16
	#define TIM5_CAPCOM_TIF_vector               0x16
	#define TIM5_CAPCOM_CC2IF_vector             0x16
	#define TIM5_CAPCOM_CC1IF_vector             0x16
	#define USART1_R_RXNE_vector                 0x1C
	#define USART1_R_OR_vector                   0x1C
	#define USART1_R_IDLE_vector                 0x1C
	#define USART1_R_PE_vector                   0x1C
	#define I2C_SB_vector                        0x1D
	#define I2C_ADDR_vector                      0x1D
	#define I2C_ADD10_vector                     0x1D
	#define I2C_STOPF_vector                     0x1D
	#define I2C_BTF_vector                       0x1D
	#define I2C_WUFH_vector                      0x1D
	#define I2C_RXNE_vector                      0x1D
	#define I2C_TXE_vector                       0x1D
	#define I2C_BERR_vector                      0x1D
	#define I2C_ARLO_vector                      0x1D
	#define I2C_AF_vector                        0x1D
	#define I2C_OVR_vector                       0x1D
#endif
//************************************************************************************
#endif
